# Generated by Django 3.0.8 on 2020-11-12 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='curso',
            name='participante',
        ),
        migrations.AddField(
            model_name='curso',
            name='participante',
            field=models.ManyToManyField(related_name='usuario_participante', to='cursos_pagamento.Usuario'),
        ),
    ]
