# Generated by Django 3.0.8 on 2020-11-13 00:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0002_auto_20201112_1806'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='data_inicio',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='data_termino',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='curso',
            name='has_finished',
            field=models.BooleanField(default=False, verbose_name='curso finalizado'),
        ),
        migrations.AddField(
            model_name='curso',
            name='has_started',
            field=models.BooleanField(default=False, verbose_name='curso iniciado'),
        ),
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('relatorio', models.FileField(upload_to='relatorio/<django.db.models.fields.related.OneToOneField>/%d/%m/%Y/')),
                ('curso', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='cursos_pagamento.Curso')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='atividade_usuario_participante', to='cursos_pagamento.Usuario')),
            ],
        ),
    ]
