# Generated by Django 3.0.8 on 2020-11-13 00:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0003_auto_20201112_2136'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='situacao_curso',
            field=models.CharField(choices=[('NOVO', 'novo'), ('INICIADO', 'iniciado'), ('FINALIZADO', 'finalizado')], default='NOVO', max_length=20),
        ),
    ]
