# Generated by Django 3.0.8 on 2020-11-13 21:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0006_auto_20201113_1750'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='complementacao',
            field=models.CharField(default='oi', max_length=400),
        ),
    ]
