# Generated by Django 3.0.8 on 2020-11-14 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0010_auto_20201113_2134'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='horas_trabalhadas',
            field=models.CharField(max_length=15, null=True),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='validation_date',
            field=models.DateField(default=0, editable=False),
        ),
    ]
