# Generated by Django 3.0.8 on 2020-11-14 01:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0011_auto_20201113_2202'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='horas_trabalhadas',
            field=models.CharField(default=0, max_length=15),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='validation_date',
            field=models.DateField(editable=False, null=True),
        ),
    ]
