# Generated by Django 3.0.8 on 2020-11-14 01:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0012_auto_20201113_2205'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='atividade',
            name='horas_trabalhadas',
        ),
    ]
