# Generated by Django 3.0.8 on 2020-11-14 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0014_atividade_horas_trabalhadas'),
    ]

    operations = [
        migrations.AlterField(
            model_name='atividade',
            name='horas_trabalhadas',
            field=models.CharField(max_length=15),
        ),
    ]
