# Generated by Django 3.0.8 on 2020-11-17 03:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0018_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='participante',
            field=models.ManyToManyField(through='cursos_pagamento.Atividade', to='cursos_pagamento.Usuario'),
        ),
    ]
