# Generated by Django 3.0.8 on 2020-11-17 12:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0019_auto_20201117_0026'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='usuario',
            name='user',
        ),
    ]
