# Generated by Django 3.0.8 on 2020-11-17 16:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos_pagamento', '0020_remove_usuario_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='curso',
            name='responsavel',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_responsavel', to='cursos_pagamento.Usuario'),
        ),
    ]
